version: '3'
services:
  nginx: 
    build: ./nginx-build
    container_name: proxy-nginx
    volumes:
      - ./nginx/sites-enabled/:/etc/nginx/sites-enabled/
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
#      - ./nginx/error.log:/var/log/nginx/error.log
#      - ./nginx/log/:/var/log/nginx/
      - ./nginx/cache/:/etc/nginx/cache
      - ./letsencrypt/:/etc/letsencrypt/
      - ./www/:/var/www/
    ports:
      - 80:80
      - 443:443
